#!/usr/bin/env node

/**
 * Embeds `apps/server/builtin-skills/**` into `src/skills/builtinSkills.gen.ts`.
 *
 * The server runs as raw TypeScript in dev, as a bundle, and as a single-file
 * executable, and only the last two could carry loose asset files. Embedding
 * the files as strings reaches all three. Run after editing a built-in skill:
 *
 *   node apps/server/scripts/generate-builtin-skills.ts
 *
 * `builtinSkills.test.ts` fails when the generated module is stale.
 */
import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";

export const renderBuiltinSkillsModule = Effect.fn("renderBuiltinSkillsModule")(function* (
  skillsSourceDir: string,
) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const entries = yield* fs.readDirectory(skillsSourceDir, { recursive: true });
  const files: Array<{ path: string; executable: boolean; contents: string }> = [];
  for (const entry of entries.toSorted()) {
    const absolute = path.join(skillsSourceDir, entry);
    const info = yield* fs.stat(absolute);
    if (info.type !== "File") continue;
    files.push({
      path: entry.split(path.sep).join("/"),
      executable: (info.mode & 0o111) !== 0,
      contents: yield* fs.readFileString(absolute),
    });
  }
  const rows = files.map(
    (file) =>
      `  {\n    path: ${JSON.stringify(file.path)},\n    executable: ${file.executable},\n    contents: ${JSON.stringify(file.contents)},\n  },`,
  );
  return `// Generated by apps/server/scripts/generate-builtin-skills.ts from apps/server/builtin-skills. Do not edit.

export interface BuiltinSkillFile {
  /** POSIX path relative to the skills root, starting with the skill's directory. */
  readonly path: string;
  readonly executable: boolean;
  readonly contents: string;
}

export const BUILTIN_SKILL_FILES: ReadonlyArray<BuiltinSkillFile> = [
${rows.join("\n")}
];
`;
});

export const builtinSkillsPaths = Effect.gen(function* () {
  const path = yield* Path.Path;
  const serverDir = path.resolve(import.meta.dirname, "..");
  return {
    sourceDir: path.join(serverDir, "builtin-skills"),
    modulePath: path.join(serverDir, "src", "skills", "builtinSkills.gen.ts"),
  };
});

if (import.meta.main) {
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const { sourceDir, modulePath } = yield* builtinSkillsPaths;
    yield* fs.writeFileString(modulePath, yield* renderBuiltinSkillsModule(sourceDir));
  }).pipe(Effect.provide(NodeServices.layer), NodeRuntime.runMain);
}
